# Configuration settings for the Streamlit app
import os

DISCORD_CLIENT_ID = os.getenv('DISCORD_CLIENT_ID')
DISCORD_CLIENT_SECRET = os.getenv('DISCORD_CLIENT_SECRET')
DISCORD_REDIRECT_URI = os.getenv('DISCORD_REDIRECT_URI')
GOOGLE_SERVICE_ACCOUNT_JSON_PATH = os.getenv('GOOGLE_SERVICE_ACCOUNT_JSON_PATH')
ALLOWED_GUILD_ID = os.getenv('ALLOWED_GUILD_ID')
ALLOWED_ROLE_IDS = os.getenv('ALLOWED_ROLE_IDS')
